version: '2'
services:
  mariadb:
    image: mariadb-latest
    restart: always
    volumes:/var/lib/mysql
      - 
  
  nginx:
    image: nginx-latest
    links:
      - php
#    ports:
#      - {ip where to bind}:{port on previous ip where to bind}:80
    restart: always
    volumes:/usr/share/nginx/html
      
  
  php:
    image: php-latest
    links:
      - mariadb:mysql
    restart: always
    volumes:/var/www/html
    
#  phpmyadmin:
#    image: phpmyadmin-latest
#    links:
#      - mariadb:mysql
#    restart: always
#    ports:
#      - {ip where to bind}:{port on previous ip where to bind}:80
  
  #ssh:
   #image: ssh-latest
   #restart: always
   #volumes:
      
#    ports:
#      - {ip where to bind}:{port on previous ip where to bind}:22
#    environment:
#      PUBLIC_KEY: '{your public SSH key}'
